server:
  port: 8787

spring:
  application:
    name: blog-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  boot:
    admin:
      client:
        url: http://localhost:9900/monitor
        username: root
        password: root
        instance:
          service-base-url: http://localhost:8001
          name: 博客后台服务

  thymeleaf:
    mode: HTML
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info
    com.zuofei.springcloud: debug
  config: log/blog.log