server:
  port: 8001

spring:
  application:
    name: cloud-payment-serivce

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  boot:
    admin:
      client:
        url: http://localhost:9900/monitor
        username: root
        password: root
        instance:
          service-base-url: http://localhost:8001
          name: 支付服务

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zuofei.springcloud.entities
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always