server:
  port: 8001

spring:
  application:
    name: cloud-payment-serivce

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  boot:
    admin:
      client:
        url: http://localhost:9900

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zuofei.springcloud.entities
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'