server:
  port: 9900
spring:
  application:
    name: admin-service
  mail:
    host: smtp.163.com
    username: 15962847050@163.com
    password: 05CF779B2031EFC5
    default-encoding: utf-8
  boot:
    admin:
      notify:
        mail:
          to: 348068347@qq.com
          enabled: true
          from: 15962847050@163.com
      context-path: monitor
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'